/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cam_test_Sample3View */

#ifndef SPY_DEMO_CAMERA_STREAM_HH_
#define SPY_DEMO_CAMERA_STREAM_HH_
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_spy_demo_CameraStream_tracking(JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);
JNIEXPORT void JNICALL Java_spy_demo_CameraStream_backgroundsubstraction(JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
